export default [
  { id: 1, name: 'hommbase', link: 'https://hommbase.ru/', github: 'https://github.com/Nitrosick/Hommbase_New', stack: ['Vue', 'Nuxt', 'PHP', 'MySQL'], description: 'The knowledge base for the game Heroes of Might and Magic III' },
  { id: 2, name: 'hermitage cat reward', link: 'https://cats.pervye.ru/', stack: ['Vue', 'Nuxt'], description: 'A Web project of all-Russian children`s drawing competition' },
  { id: 3, name: 'adites', link: 'http://adites-beratung.de/', github: 'https://github.com/Nitrosick/Adites', stack: ['Vue', 'Nuxt'], description: 'A custom made project for a company that sells solar panels and other "Green energy" components.' },
  { id: 4, name: 'meteoread', link: 'http://nitros66.beget.tech/projects/meteoread/index.html', github: 'https://github.com/Nitrosick/Meteoread', stack: ['Vue'], description: 'Meteo application that shows weather data for the entered city. The data comes from the OpenWeatherMap API.' },
  { id: 5, name: 'webtronics', link: 'http://nitros66.beget.tech/projects/webtronics/index.html', github: 'https://github.com/Nitrosick/Webtronics_task', stack: ['React', 'TypeScript'], description: 'Layout of a single-page application for developers. The project uses React Hook Form to work with forms and Yup.js for data validation' },
  { id: 6, name: 'infinizai', link: 'http://nitros66.beget.tech/projects/infinizai/index.html', github: 'https://github.com/Nitrosick/Infinizai', stack: ['React'], description: 'A full-fledged playground layout from Figma. Adaptable for all types of devices. Animations are created using Framer Motion JS.' },
  { id: 7, name: 'brand shop', link: 'http://nitros66.beget.tech/projects/brand_shop/index.html', github: 'https://github.com/Nitrosick/GB_Layouts/tree/main/Brand%20Shop', stack: ['HTML5', 'CSS3', 'JavaScript'], description: 'Layout of an online store of branded clothing. It is written in native languages. One of the first educational projects in GeekBrains.' },
  { id: 8, name: 'dconto', link: 'http://nitros66.beget.tech/projects/dconto/index.html', github: 'https://github.com/Nitrosick/DepositFM_task', stack: ['HTML5', 'CSS3', 'JavaScript'], description: 'Layout of a real estate search site. It is written in native languages. Custom forms and pop-ups. The layout is adapted for mobile devices.' }
]
